<MyBox>:
    orientation: 'vertical'
    spacing: 50
    padding: [20,40,60,80]
    Button:
        text: 'B1'
        on_press: print('--> B1')
        pos_hint: {'x' : .1}
        size_hint: [.2,1]
    Button:
        text: 'B2'
        on_press: print('--> B2')
        pos_hint: {'center_x' : .3}
        size_hint: [.2,2]
    Button:
        text: 'B3'
        on_press: print('--> B3')
        pos_hint: {'right': 1}
        size_hint: [.4,1]
