
function carregarItensSelect() {
  var select = document.getElementById('pais');
  var i = 0;
  var tamanho = pais.length;
  for (; i < tamanho; i++) {
    var option = document.createElement('option');
    option.setAttribute('value', pais[i]);
    option.appendChild(document.createTextNode(pais[i]));
    select.appendChild(option);
  }
}

var pais = [
'',
'Afeganistão',
'Acrotíri e Decelia',
'África do Sul',
'Albânia',
'Alemanha',
'American Samoa',
'Andorra',
'Angola',
'Anguilla',
'Antígua e Barbuda',
'Antilhas Neerlandesas',
'Arábia Saudita',
'Argélia',
'Argentina',
'Arménia',
'Aruba',
'Austrália',
'Áustria',
'Azerbaijão',
'Bahamas',
'Bangladeche',
'Barbados',
'Barém',
'Bassas da Índia',
'Bélgica',
'Belize',
'Benim',
'Bermudas',
'Bielorrússia',
'Bolívia',
'Bósnia e Herzegovina',
'Botsuana',
'Brasil',
'Brunei Darussalam',
'Bulgária',
'Burquina Faso',
'Burundi',
'Butão',
'Cabo Verde',
'Camarões',
'Camboja',
'Canadá',
'Catar',
'Cazaquistão',
'Centro-Africana República',
'Chade',
'Chile',
'China',
'Chipre',
'Colômbia',
'Comores',
'Congo',
'Congo República Democrática',
'Coreia do Norte',
'Coreia do Sul',
'Costa do Marfim',
'Costa Rica',
'Croácia',
'Cuba',
'Dinamarca',
'Domínica',
'Egipto',
'Emirados Árabes Unidos',
'Equador',
'Eritreia',
'Eslováquia',
'Eslovénia',
'Espanha',
'Estados Unidos',
'Estónia',
'Etiópia',
'Faixa de Gaza',
'Fiji',
'Filipinas',
'Finlândia',
'França',
'Gabão',
'Gâmbia',
'Gana',
'Geórgia',
'Gibraltar',
'Granada',
'Grécia',
'Gronelândia',
'Guadalupe',
'Guam',
'Guatemala',
'Guernsey',
'Guiana',
'Guiana Francesa',
'Guiné',
'Guiné Equatorial',
'Guiné-Bissau',
'Haiti',
'Honduras',
'Hong Kong',
'Hungria',
'Iémen',
'Ilha Bouvet',
'Ilha Christmas',
'Ilha de Clipperton',
'Ilha de João da Nova',
'Ilha de Man',
'Ilha de Navassa',
'Ilha Europa',
'Ilha Norfolk',
'Ilha Tromelin',
'Ilhas Ashmore e Cartier',
'Ilhas Caiman',
'Ilhas Cocos (keeling)',
'Ilhas Cook',
'Ilhas do Mar de Coral',
'Ilhas Falklands (ilhas malvinas)',
'Ilhas Feroe',
'Ilhas Geórgia do sul e sandwich do sul',
'Ilhas Marianas do norte',
'Ilhas Marshall',
'Ilhas Paracel',
'Ilhas Pitcairn',
'Ilhas Salomão',
'Ilhas Spratly',
'Ilhas Virgens americanas',
'Ilhas Virgens britânicas',
'Índia',
'Indonésia',
'Irão',
'Iraque',
'Irlanda',
'Islândia',
'Israel',
'Itália',
'Jamaica',
'Jan Mayen',
'Japão',
'Jersey',
'Jibuti',
'Jordânia',
'Kiribati',
'Koweit',
'Laos',
'Lesoto',
'Letónia',
'Líbano',
'Libéria',
'Líbia',
'Listenstaine',
'Lituânia',
'Luxemburgo',
'Macau',
'Macedónia',
'Madagáscar',
'Malásia',
'Malavi',
'Maldivas',
'Mali',
'Malta',
'Marrocos',
'Martinica',
'Maurícia',
'Mauritânia',
'Mayotte',
'México',
'Mianmar',
'Micronésia',
'Moçambique',
'Moldávia',
'Mónaco',
'Mongólia',
'Montenegro',
'Montserrat',
'Namíbia',
'Nauru',
'Nepal',
'Nicarágua',
'Níger',
'Nigéria',
'Niue',
'Noruega',
'Nova Caledónia',
'Nova Zelândia',
'Omã',
'Países Baixos',
'Palau',
'Palestina',
'Panamá',
'Papuásia-Nova Guiné',
'Paquistão',
'Paraguai',
'Peru',
'Polinésia Francesa',
'Polónia',
'Porto Rico',
'Portugal',
'Quénia',
'Quirguizistão',
'Reino Unido',
'República Checa',
'República Dominicana',
'Roménia',
'Ruanda',
'Rússia',
'Sahara Occidental',
'Salvador',
'Samoa',
'Santa Helena',
'Santa Lúcia',
'Santa Sé',
'São Cristóvão e Neves',
'São Marino',
'São Pedro e Miquelão',
'São Tomé e Príncipe',
'São Vicente e Granadinas',
'Seicheles',
'Senegal',
'Serra Leoa',
'Sérvia',
'Singapura',
'Síria',
'Somália',
'Sri Lanca',
'Suazilândia',
'Sudão',
'Suécia',
'Suíça',
'Suriname',
'Svalbard',
'Tailândia',
'Taiwan',
'Tajiquistão',
'Tanzânia',
'Território Britânico do Oceano índico',
'Território das Ilhas Heard e Mcdonald',
'Timor-Leste',
'Togo',
'Tokelau',
'Tonga',
'Trindade e Tobago',
'Tunísia',
'Turks e Caicos',
'Turquemenistão',
'Turquia',
'Tuvalu',
'Ucrânia',
'Uganda',
'Uruguai',
'Usbequistão',
'Vanuatu',
'Venezuela',
'Vietname',
'Wallis e Futuna',
'Zâmbia',
'Zimbabué'
];
