#:import rnd random

<ColorTriangle>:
    size_hint: None, None
    size: 25,50
    canvas:
        Color:
            rgb: rnd.random(),rnd.random(),rnd.random()
        Triangle:
            points:
                (self.x,self.y, self.x+self.width,self.y,
                self.x+self.width/2,self.y+self.height)
            
<Ex34>:
    canvas:
        Color:
            rgb: .9,.8,1
        Rectangle:
            size: root.size
            pos: root.pos
